package com.config;

public enum RevenantWeapon {
    VIGGORACHARGED,
    URSINECHARGED,
    CRAWCHARGED,
    WEBWEAVERCHARGED,
    VIGGORAUNCHARGED,
    URSINEUNCHARGED,
    AUTOTHAMCHARGED,
    THAMCHARGED,
    AUTOACCCHARGED,
    ACCCHARGED,
    CRAWUNCHARGED,
    WEBWEAVERUNCHARGED,
    AUTOTHAMUNCHARGED,
    THAMUNCHARGED,
    AUTOACCUNCHARGED,
    ACCUNCHARGED,
    NOT_REV_WEAPON
}
